// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam/test/domain/use_case/profile/change_password_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:online_exam/core/network/api_result.dart' as _i4;
import 'package:online_exam/data/models/profile/change_password_request.dart'
    as _i8;
import 'package:online_exam/data/models/profile/edit_profile_request.dart'
    as _i7;
import 'package:online_exam/domain/entities/user_entity.dart' as _i5;
import 'package:online_exam/domain/repository/profile_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.UserEntity>> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i3.Future<_i4.ApiResult<_i5.UserEntity>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.UserEntity>>(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UserEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.UserEntity>> editProfile(
    _i7.EditProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [request]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.UserEntity>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.UserEntity>>(
                this,
                Invocation.method(#editProfile, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UserEntity>>);

  @override
  _i3.Future<_i4.ApiResult<void>> changePassword(
    _i8.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i3.Future<_i4.ApiResult<void>>.value(
              _i6.dummyValue<_i4.ApiResult<void>>(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<void>>);
}
