// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam/test/data/datasource/implementation/profile_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam/core/network/base_response.dart' as _i2;
import 'package:online_exam/data/api/api_client.dart' as _i7;
import 'package:online_exam/data/models/auth/forgot_password_request.dart'
    as _i9;
import 'package:online_exam/data/models/auth/login_request.dart' as _i12;
import 'package:online_exam/data/models/auth/login_response.dart' as _i3;
import 'package:online_exam/data/models/auth/logout_response.dart' as _i4;
import 'package:online_exam/data/models/auth/reset_password_request.dart'
    as _i11;
import 'package:online_exam/data/models/auth/verify_reset_code_request.dart'
    as _i10;
import 'package:online_exam/data/models/profile/change_password_request.dart'
    as _i14;
import 'package:online_exam/data/models/profile/change_password_response.dart'
    as _i6;
import 'package:online_exam/data/models/profile/edit_profile_request.dart'
    as _i13;
import 'package:online_exam/data/models/profile/profile_response.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutResponse_2 extends _i1.SmartFake
    implements _i4.LogoutResponse {
  _FakeLogoutResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileResponse_3 extends _i1.SmartFake
    implements _i5.ProfileResponse {
  _FakeProfileResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponse_4 extends _i1.SmartFake
    implements _i6.ChangePasswordResponse {
  _FakeChangePasswordResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i7.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.BaseResponse<void>> forgotPassword(
    _i9.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i8.Future<_i2.BaseResponse<void>>.value(
              _FakeBaseResponse_0<void>(
                this,
                Invocation.method(#forgotPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i2.BaseResponse<void>>);

  @override
  _i8.Future<_i2.BaseResponse<void>> verifyResetCode(
    _i10.VerifyResetCodeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i8.Future<_i2.BaseResponse<void>>.value(
              _FakeBaseResponse_0<void>(
                this,
                Invocation.method(#verifyResetCode, [request]),
              ),
            ),
          )
          as _i8.Future<_i2.BaseResponse<void>>);

  @override
  _i8.Future<_i2.BaseResponse<void>> resetPassword(
    _i11.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i8.Future<_i2.BaseResponse<void>>.value(
              _FakeBaseResponse_0<void>(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i2.BaseResponse<void>>);

  @override
  _i8.Future<_i3.LoginResponse> login(_i12.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i8.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i8.Future<_i3.LoginResponse>);

  @override
  _i8.Future<_i4.LogoutResponse> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<_i4.LogoutResponse>.value(
              _FakeLogoutResponse_2(this, Invocation.method(#logout, [])),
            ),
          )
          as _i8.Future<_i4.LogoutResponse>);

  @override
  _i8.Future<_i5.ProfileResponse> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i8.Future<_i5.ProfileResponse>.value(
              _FakeProfileResponse_3(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i8.Future<_i5.ProfileResponse>);

  @override
  _i8.Future<_i5.ProfileResponse> editProfile(
    _i13.EditProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [request]),
            returnValue: _i8.Future<_i5.ProfileResponse>.value(
              _FakeProfileResponse_3(
                this,
                Invocation.method(#editProfile, [request]),
              ),
            ),
          )
          as _i8.Future<_i5.ProfileResponse>);

  @override
  _i8.Future<_i6.ChangePasswordResponse> changePassword(
    _i14.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i8.Future<_i6.ChangePasswordResponse>.value(
              _FakeChangePasswordResponse_4(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i6.ChangePasswordResponse>);
}
